### ISSUE TITLE
Geniki Taxydromiki always returning no result

### ISSUE THREAD

**Issue by ComradeTurtle** [ComradeTurtle/courier-api#3]
**Describe the bug**
All tracking numbers queried using Geniki Taxydromiki always return no result regardless of the actual status of the package.

**Expected behavior**
The module is expected to return the tracking history.

**Comment by tougrel** [comment]
I'm gonna test this and update this ASAP :+1:

**Comment by ComradeTurtle** [comment]
This should be fixed by commit 59206790cd35f3a54414cca73bd9eaf0ff8c581a - I will be testing it as soon as possible.
